### ISSUE TITLE
Implementing content detail page as widget

### ISSUE THREAD

**Issue by vinukumar-vs** [Sunbird-Ed/SunbirdEd-portal#8656]
# Project Details

**What is Sunbird-Portal?**

[Sunbird](http://sunbird.org/) is a next-generation scalable open-source learning solution for teachers and tutors. Built for the 21st century with [state-of-the-art technology](http://www.sunbird.org/architecture/views/physical/), Sunbird runs natively in [cloud/mobile environments](http://www.sunbird.org/features/). The [open-source governance](https://github.com/Sunbird-Ed/SunbirdEd-portal/blob/master/LICENSE) of Sunbird allows a massive community of nation-builders to co-create and extend the solution in novel ways.

https://github.com/Sunbird-Ed/SunbirdEd-portal#what-is-sunbird

# Features to be implemented
Content/Collection detail page should be the Title, details/metadata of the content & TOC(for Collections) should work as an independent widget. So that widget can be taken into any other project without any code change they should able to integrate the details page. It should be responsive for mobile/web pages.
Widget should be configurable to change the layout or options to hide/show elements. This will help to adopt the content details page to any project by configuration changes.

**What exists:**
* The content details page is implemented with multiple sunbird Common consumption components & specific code in the portal to render the page.
* The content detail page is also having content-player to play the content(different players are integrated to play different type of contents).

**What needs to be build**
* Converting the entire page as independent widget & the current functionality should work as is by configuration & passing the data.
* Documentation of how to configure properties
* Documentation of how to extend or customise the widget
* Test cases for the widget capabilities

# Learning Path

### Complexity 
High

### Skills Required
Angular

### Name of Mentors
@rajeevsathish 

### Project size
?? Weeks - TBD

# Product Set Up
https://github.com/Sunbird-Ed/SunbirdEd-portal#readme

# Acceptance Criteria
- [ ] Content details page are rendering properly in different resolutions(web & mobile view)
- [ ] Content detail page is configurable to show/hide specific elements
- [ ] Content detail page is able to play the supported content type(PDF, Video, EPUB, HTML, H5P etc..)
- [ ] Content details page can be used to show the collections(TOC will be visible)
- [ ] Telemetry is generating for all the workflows

# Out of Scope

# Milestones

- [ ] Content detail page is showing for any one content type(PDF contents)
- [ ] Content player is capable of playing the different content types which are supported today
- [ ] Content detail page is able to show collections along with TOC

**Comment by vinukumar-vs** [comment]
[C4GT](https://www.codeforgovtech.in/) problem statement
@Krishnaj20 @rajeevsathish @SanthoshVasabhaktula @vrayulu

**Comment by chandra-pro** [comment]
Hii @vinukumar-vs I am intrested to contribute this issue.Could you please guide me where is the existing repo where i make changes?

**Comment by vinukumar-vs** [comment]
I would suggest you to check the below once and understand what code being used
https://github.com/Sunbird-Ed/SunbirdEd-portal/tree/6.0v14/src/app/client/src/app/modules/shared-feature/components/content-player

Play with below url's to understand
https://staging.sunbirded.org/play/content/do_21344970717646028811073?contentType=ClassroomTeachingVideo
https://staging.sunbirded.org/play/content/do_21344973349303910411481?contentType=eTextBook

@rajeevsathish Let's connect with him to explain the code & webcomponent.

Meanwhile you can think how to make it front-end code agnostic by implementing as widget
https://www.webcomponents.org/introduction

@swayangjit

**Comment by Anshika-sona** [comment]
Hey , can you assign me this? I am interested to work on this.

**Comment by chandra-pro** [comment]
Time is already over..

**Comment by Kanikawadhwa28** [comment]
Can you please assign me this ....since the deadline is till today midnight so I'll try to make the best use of the opportunity and I still have 7 hours . Please sir I request you.
