### ISSUE TITLE
Implementing SSO flow as an Independent plug-able NPM package

### ISSUE THREAD

**Issue by rajeevsathish** [Sunbird-Ed/SunbirdEd-portal#8666]
# Project Details

**What is Sunbird-Portal?**

[Sunbird](http://sunbird.org/) is a next-generation scalable open-source learning solution for teachers and tutors. Built for the 21st century with [state-of-the-art technology](http://www.sunbird.org/architecture/views/physical/), Sunbird runs natively in [cloud/mobile environments](http://www.sunbird.org/features/). The [open-source governance](https://github.com/Sunbird-Ed/SunbirdEd-portal/blob/master/LICENSE) of Sunbird allows a massive community of nation-builders to co-create and extend the solution in novel ways.

https://github.com/Sunbird-Ed/SunbirdEd-portal#what-is-sunbird

# Features to be implemented

The feature to be implemented is to make the login configurable and plug-able item as an NPM module
specifically the SSO module in sunbird.

**What exists:**
In sunbird there are multiple login types
	1. The user can register him/her self and post registering they can use the email or Phone number to login into the system
	2. The user can register using the gmail and login into the system
	3. If a user is state user then he/she can use the state login to register and login into the system

The third option is more of a DIKSHA specific use-case. So make it as a plug-able item in sunbird system.

**What needs to be build**

- Implement the SSO feature in login as a plug-able NPM module and can be used by any required use-case.
- Documentation of how to configure properties
- Documentation of how to extend or customise the widget
- Test cases for the widget capabilities

# Learning Path

### Complexity 
High

### Skills Required
Angular

### Name of Mentors
@rajeevsathish @rajeshkumaravel

### Project size
?? Weeks - TBD

# Product Set Up
https://github.com/Sunbird-Ed/SunbirdEd-portal#readme

# Acceptance Criteria

- [ ] Login workflow works properly with the plugin or without the plugin

- [ ] Once configured the SSO login will show

- [ ] SSO login flow works with out any issue

- [ ] Telemetry is generating for all the workflows
# Out of Scope

# Milestones

- [ ] Login Works with the existing types.
- [ ] Configurable SSO flow

**Comment by Shruti3004** [comment]
Hey @rajeevsathish thanks for detailing this out, can you please remove or add the details in out of scope. Thanks!

**Comment by devanshu0605** [comment]
Hey mentor,

I hope you're doing well. I wanted to express my interest in contributing to this project. I have experience and familiarity with Angular, and I believe I can make valuable contributions.

**Comment by om-666** [comment]
Dear Sir, I have been shortlisted for this project, but my name is not listed among the assignees. What should be my next step? I am eager to contribute to this project.
