### ISSUE TITLE
[C4GT] - Review enhancements

### ISSUE THREAD

**Issue by coolbung** [Sunbird-Ed/SunbirdEd-portal#8691]
## Project Details

Currently in SB, when a content is sent for review, all users who have review roles can review  that content. This is not very effective when a creator wants to get the content reviewed by subject matter experts.

Also, currently SB supports contents to be reviewed by only one reviewer. In certain scenarios, the reviewer may decide a need for further review of the contents and she can send the content for further review to another user.

## Features to be implemented
- [ ] Ability to create groups of reviewers (maybe use existing groups in sunbird)
- [ ] When sending a content for review, the creator can optionally specify which reviewer group should review the content (anyone from that group may review)
- [ ] When a reviewer reviews the content, they can choose to publish, or ask for another review from a specific reviewer or a group

**What exists**

Currently, the flow is fixed such that when the creator sends for review, any reviewer from the org can review it. 

## Learning Path

**Complexity** High

**Skills Required**

- Java / Scala for backend
- Flink
- kafka

Name of Mentors
TBD

Project size
12 Weeks

Product Set Up
https://github.com/Sunbird-Ed/SunbirdEd-portal#readme

## Acceptance Criteria
TBD

## Out of Scope
TBD

## Milestones
TBD

**Comment by VOSID8** [comment]
Hello, 
I am a Scala enthusiast and am interested in contributing. My knowledge includes Scala with SMACK Stack, Play, and other frameworks. Also, having strong Python skills.  Please release the Acceptance criteria and other missing fields. 
And how to proceed and start. Thanks alot
